authEnabled: true
logging:
  level: INFO
  loggers:
    "org.zenoss": INFO
queryApp:
  httpClient:
    # parameters to configure connection pool for querying OpenTsdb:
    # Total connections allowed per pool
    maxConnections: 100
    # Max number of connections for a given route
    maxConnectionsPerRoute: 100

  defaultReturnSet: EXACT
  defaultStartTime: 1h-ago
  defaultEndTime: now
  defaultSeries: true
  openTsdbUrl: http://127.0.0.1:4242
  defaultTsdTimeZone: UTC
  connectionTimeoutMs: 20000
  sendRateOptions: false


  # parameters to configure thread pool for querying OpenTsdb:
  # Core number of threads in thread pool
  executorThreadPoolCoreSize: 20
  # Maximum number of threads in thread pool
  executorThreadPoolMaxSize: 250

proxyConfiguration:
  hostname: 127.0.0.1
  port: 8080

server:
  applicationConnectors:
    - type: http
      port: 8888
  adminConnectors:
    - type: http
      port: 58888

#managedReporter:
#    metricReporters:
#      - {posterType: http, username: "$env[CONTROLPLANE_CONSUMER_USERNAME]", password: "$env[CONTROLPLANE_CONSUMER_PASSWORD]", urlEnvironment: "CONTROLPLANE_CONSUMER_URL"}
#      - {posterType: http, username: "$zcreds[]", password: "$zcreds[]", protocol: http, host: localhost, port: 8080, apiPath: /api/metrics/store}
